/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversordivisas.view;

import conversordivisas.view.utils.ComboBoxCustom;
import conversordivisas.view.utils.FrameDragger;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Mario
 */
public class FrameDivisas extends javax.swing.JFrame {

    /**
     * Creates new form FrameDivisas
     */
    public FrameDivisas() {
        
        setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        
        
        initComponents();
        
        panelFondo.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        
       FrameDragger frameDragger;
       frameDragger = new FrameDragger(panelFondo, this);
       
       ComboBoxCustom comboBoxCustom;
       comboBoxCustom = new ComboBoxCustom(comboboxConvertirDe);
       comboBoxCustom = new ComboBoxCustom(comboboxConvertirA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblMinus = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblSubtitulo2 = new javax.swing.JLabel();
        lblConvertirDe = new javax.swing.JLabel();
        comboboxConvertirDe = new javax.swing.JComboBox();
        txtCantidad = new javax.swing.JTextField();
        lblIconDolar = new javax.swing.JLabel();
        imgConvertirDe = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        imgCantidad = new javax.swing.JLabel();
        lblConvertirA = new javax.swing.JLabel();
        comboboxConvertirA = new javax.swing.JComboBox();
        imgConvertirA = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        lblResultado2 = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        lblCopyRight = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelFondo.setPreferredSize(new java.awt.Dimension(400, 700));
        panelFondo.setLayout(null);

        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/exit.png"))); // NOI18N
        lblExit.setPreferredSize(new java.awt.Dimension(14, 14));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        panelFondo.add(lblExit);
        lblExit.setBounds(350, 20, 14, 14);

        lblMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/minus.png"))); // NOI18N
        lblMinus.setPreferredSize(new java.awt.Dimension(14, 14));
        lblMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinusMouseExited(evt);
            }
        });
        panelFondo.add(lblMinus);
        lblMinus.setBounds(320, 20, 14, 14);

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Conversor de Divisas");
        lblTitulo.setPreferredSize(new java.awt.Dimension(230, 20));
        panelFondo.add(lblTitulo);
        lblTitulo.setBounds(85, 53, 230, 20);

        lblSubtitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(4, 4, 4));
        lblSubtitulo.setText("te mostrará cuánto vale tu dinero en otras");
        lblSubtitulo.setPreferredSize(new java.awt.Dimension(270, 12));
        panelFondo.add(lblSubtitulo);
        lblSubtitulo.setBounds(65, 100, 270, 12);

        lblSubtitulo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtitulo2.setForeground(new java.awt.Color(4, 4, 4));
        lblSubtitulo2.setText("monedas al tipo de cambio real.");
        lblSubtitulo2.setPreferredSize(new java.awt.Dimension(270, 12));
        panelFondo.add(lblSubtitulo2);
        lblSubtitulo2.setBounds(65, 112, 270, 12);

        lblConvertirDe.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblConvertirDe.setText("Convertir de");
        lblConvertirDe.setPreferredSize(new java.awt.Dimension(100, 14));
        panelFondo.add(lblConvertirDe);
        lblConvertirDe.setBounds(30, 150, 100, 14);

        comboboxConvertirDe.setBackground(new java.awt.Color(226, 226, 226));
        comboboxConvertirDe.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        comboboxConvertirDe.setForeground(new java.awt.Color(49, 63, 91));
        comboboxConvertirDe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxConvertirDe.setBorder(null);
        comboboxConvertirDe.setFocusable(false);
        comboboxConvertirDe.setPreferredSize(new java.awt.Dimension(330, 50));
        comboboxConvertirDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboboxConvertirDeMouseClicked(evt);
            }
        });
        panelFondo.add(comboboxConvertirDe);
        comboboxConvertirDe.setBounds(35, 182, 330, 50);

        txtCantidad.setBackground(new java.awt.Color(226, 226, 226));
        txtCantidad.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(49, 63, 91));
        txtCantidad.setBorder(null);
        txtCantidad.setPreferredSize(new java.awt.Dimension(309, 50));
        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadMouseClicked(evt);
            }
        });
        panelFondo.add(txtCantidad);
        txtCantidad.setBounds(58, 297, 309, 50);

        lblIconDolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconDolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/signo_dollar.png"))); // NOI18N
        lblIconDolar.setPreferredSize(new java.awt.Dimension(25, 50));
        lblIconDolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconDolarMouseClicked(evt);
            }
        });
        panelFondo.add(lblIconDolar);
        lblIconDolar.setBounds(35, 297, 25, 50);

        imgConvertirDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgConvertirDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/input.png"))); // NOI18N
        imgConvertirDe.setPreferredSize(new java.awt.Dimension(344, 65));
        panelFondo.add(imgConvertirDe);
        imgConvertirDe.setBounds(30, 175, 344, 65);

        lblCantidad.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCantidad.setText("Cantidad");
        lblCantidad.setPreferredSize(new java.awt.Dimension(100, 14));
        panelFondo.add(lblCantidad);
        lblCantidad.setBounds(30, 266, 100, 14);

        imgCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/input.png"))); // NOI18N
        imgCantidad.setPreferredSize(new java.awt.Dimension(344, 64));
        panelFondo.add(imgCantidad);
        imgCantidad.setBounds(30, 290, 344, 64);

        lblConvertirA.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblConvertirA.setText("Convertir A");
        lblConvertirA.setPreferredSize(new java.awt.Dimension(100, 14));
        panelFondo.add(lblConvertirA);
        lblConvertirA.setBounds(30, 382, 100, 14);

        comboboxConvertirA.setBackground(new java.awt.Color(226, 226, 226));
        comboboxConvertirA.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        comboboxConvertirA.setForeground(new java.awt.Color(49, 63, 91));
        comboboxConvertirA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxConvertirA.setBorder(null);
        comboboxConvertirA.setFocusable(false);
        comboboxConvertirA.setPreferredSize(new java.awt.Dimension(330, 50));
        comboboxConvertirA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboboxConvertirAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboboxConvertirAMouseEntered(evt);
            }
        });
        panelFondo.add(comboboxConvertirA);
        comboboxConvertirA.setBounds(35, 414, 330, 50);

        imgConvertirA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgConvertirA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/input.png"))); // NOI18N
        imgConvertirA.setPreferredSize(new java.awt.Dimension(344, 65));
        panelFondo.add(imgConvertirA);
        imgConvertirA.setBounds(30, 407, 344, 65);

        lblResultado.setFont(new java.awt.Font("Arial", 1, 19)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(69, 82, 107));
        lblResultado.setText("10 Dólares estadounidenses =");
        lblResultado.setPreferredSize(new java.awt.Dimension(340, 18));
        panelFondo.add(lblResultado);
        lblResultado.setBounds(30, 500, 340, 18);

        lblResultado2.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        lblResultado2.setForeground(new java.awt.Color(49, 63, 91));
        lblResultado2.setText("9 Euros");
        lblResultado2.setPreferredSize(new java.awt.Dimension(340, 26));
        panelFondo.add(lblResultado2);
        lblResultado2.setBounds(30, 530, 340, 26);

        btnConvertir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/btnConvertir.png"))); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.setBorder(null);
        btnConvertir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConvertir.setPreferredSize(new java.awt.Dimension(340, 50));
        btnConvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConvertirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConvertirMouseExited(evt);
            }
        });
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        panelFondo.add(btnConvertir);
        btnConvertir.setBounds(30, 587, 340, 50);

        lblCopyRight.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCopyRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyRight.setText("Create by Mario");
        lblCopyRight.setPreferredSize(new java.awt.Dimension(120, 12));
        panelFondo.add(lblCopyRight);
        lblCopyRight.setBounds(140, 678, 120, 12);

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/background.png"))); // NOI18N
        panelFondo.add(lblBackground);
        lblBackground.setBounds(0, 0, 400, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/exitOther.png")));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversordivisas/img/exit.png")));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinusMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinusMouseClicked

    private void lblMinusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinusMouseEntered
        lblMinus.setIcon(new ImageIcon(getClass().getResource("/conversordivisas/img/minusOther.png")));
    }//GEN-LAST:event_lblMinusMouseEntered

    private void lblMinusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinusMouseExited
        lblMinus.setIcon(new ImageIcon(getClass().getResource("/conversordivisas/img/minus.png")));
    }//GEN-LAST:event_lblMinusMouseExited

    private void btnConvertirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirMouseEntered
        btnConvertir.setIcon(new ImageIcon(getClass().getResource("/conversordivisas/img/btnConvertirOther.png")));
    }//GEN-LAST:event_btnConvertirMouseEntered

    private void btnConvertirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirMouseExited
        btnConvertir.setIcon(new ImageIcon(getClass().getResource("/conversordivisas/img/btnConvertir.png")));
    }//GEN-LAST:event_btnConvertirMouseExited

    private void comboboxConvertirDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboboxConvertirDeMouseClicked
       inputSelect(imgConvertirDe, true);
    }//GEN-LAST:event_comboboxConvertirDeMouseClicked

    private void txtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseClicked
        inputSelect(imgCantidad, true);
    }//GEN-LAST:event_txtCantidadMouseClicked

    private void comboboxConvertirAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboboxConvertirAMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxConvertirAMouseEntered

    private void comboboxConvertirAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboboxConvertirAMouseClicked
        inputSelect(imgConvertirA, true);
    }//GEN-LAST:event_comboboxConvertirAMouseClicked

    private void lblIconDolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconDolarMouseClicked
        inputSelect(imgCantidad, true);
    }//GEN-LAST:event_lblIconDolarMouseClicked

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        inputSelect(imgCantidad, false);
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDivisas().setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox comboboxConvertirA;
    private javax.swing.JComboBox comboboxConvertirDe;
    private javax.swing.JLabel imgCantidad;
    private javax.swing.JLabel imgConvertirA;
    private javax.swing.JLabel imgConvertirDe;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblConvertirA;
    private javax.swing.JLabel lblConvertirDe;
    private javax.swing.JLabel lblCopyRight;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblIconDolar;
    private javax.swing.JLabel lblMinus;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblResultado2;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtitulo2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables

    private void inputSelect(JLabel inputSelect, boolean activar) {
        imgConvertirA.setIcon(new ImageIcon(getClass().getResource("/conversordivisas/img/input.png")));
        imgConvertirDe.setIcon(new ImageIcon(getClass().getResource("/conversordivisas/img/input.png")));
        imgCantidad.setIcon(new ImageIcon(getClass().getResource("/conversordivisas/img/input.png")));
        if (activar) {
            inputSelect.setIcon(new ImageIcon(getClass().getResource("/conversordivisas/img/inputOther.png")));
        }
    }
}
